apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jh7avc6yp-python 
  janus-idp.io/tekton: jh7avc6yp-python
  backstage.io/kubernetes-id: jh7avc6yp-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jh7avc6yp-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml