apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jh7avc6yp-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jh7avc6yp-python 
  name: jh7avc6yp-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jh7avc6yp-python 
